M48
; DRILL file {KiCad (6.0.5)} date Sat May 21 21:36:46 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-21T21:36:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.025Y-1.625
X2.025Y-2.775
X9.775Y-1.625
X9.775Y-2.775
T0
M30
